### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by simplyWiri** [simplyWiri/Shields#9]
Performance
- [ ] Cache and store state of colour lerping on settings change / load
- [ ] Sync up the colouring of the shields ^ related
- [ ] Limit motes spawned with multiple bullet impacts

BugFixes
- [ ] Fixing power comps, to work with rimatomics
- [ ] Fix Radius 

Compat/Integration
- [ ] Nicer Graphics for impact (impact of area flashing - closer to vanilla
- [ ] Nicer settings screen for picking colours

If I have time:
- [ ] Try re-implement compat for CCC & Dubs Hygiene
- [ ] AI, need to patch them zerging into the shields
- [ ] Damage being calculated in a more proper way for shield damage, AI reacting accordingly
